name: mc_character
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  convert: ^3.0.1
  crypto: ^3.0.1
  dio: ^4.0.1
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.1.0
  mobx: ^2.0.3
  mockito: ^5.0.16
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.6
  mobx_codegen: ^2.0.2
  
flutter:
  uses-material-design: true
